networks:
  hexstrike-asg:
    driver: bridge

services:
  kali:
    build: .
    container_name: hexstrike-kali
    profiles: [kali]
    stdin_open: true
    tty: true
    networks: [hexstrike-asg]

  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: hexstrike-dvwa
    networks: [hexstrike-asg]
    ports:
      - "0.0.0.0:4280:80"
    environment:
      - SECURITY=high # low/medium/high/impossible
    profiles: [dvwa]

